
USETEXTLINKS = 1
STARTALLOPEN = 0
USEFRAMES = 0
USEICONS = 0
WRAPTEXT = 0
PRESERVESTATE = 1
ICONPATH = "images/"

foldersTree = gFld("<b>Overview Menus</b>", "index.html")
	foldersTree.treeID = "archiving"
	aux1 = insFld(foldersTree, gFld("Locations", "javascript:undefined"))
		aux2 = insFld(aux1, gFld("<strong>Englewood/Denver</strong>", "archiving.html?Englewood-Denver"))
			aux3 = insFld(aux2, gFld("solr segments", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "solr-161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr-162", "archiving.html?solr162"))
				insDoc(aux3, gLnk("S", "solr-163", "archiving.html?solr163"))
				insDoc(aux3, gLnk("S", "solr-164", "archiving.html?solr164"))
				insDoc(aux3, gLnk("S", "solr-165", "archiving.html?solr165"))
				insDoc(aux3, gLnk("S", "solr-166", "archiving.html?solr166"))
				insDoc(aux3, gLnk("S", "solr-167", "archiving.html?solr167"))
				insDoc(aux3, gLnk("S", "solr-168", "archiving.html?solr168"))
				insDoc(aux3, gLnk("S", "solr-169", "archiving.html?solr169"))
				insDoc(aux3, gLnk("S", "solr-170", "archiving.html?solr170"))
				insDoc(aux3, gLnk("S", "solr-171", "archiving.html?solr171"))
				insDoc(aux3, gLnk("S", "solr-172", "archiving.html?solr172"))
			aux3 = insFld(aux2, gFld("Servers (solr)", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "10.1.106.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.162", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.162", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.163", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.163", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.164", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.164", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.165", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.165", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.166", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.166", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.167", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.167", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.168", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.168", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.169", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.169", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.170", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.170", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.171", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.171", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.106.172", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.1.107.172", "archiving.html?solr161"))
			aux3 = insFld(aux2, gFld("Mailsources", "archiving.html?sum-solr-segments"))
			aux3 = insFld(aux2, gFld("Top 10s", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "Ingest per day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index per Day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Ingest Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr segments", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Mailsource count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "User count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Size on Disk", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index", "archiving.html?solr161"))
		aux2 = insFld(aux1, gFld("<strong>London/Amsterdam</strong>", "archiving.html?London-Amsterdam"))
			aux3 = insFld(aux2, gFld("solr segments", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "solr-161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr-162", "archiving.html?solr162"))
			aux3 = insFld(aux2, gFld("Servers (solr)", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "10.13.106.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.13.106.162", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.162", "archiving.html?solr161"))
			aux3 = insFld(aux2, gFld("Mailsources", "archiving.html?sum-solr-segments"))
			aux3 = insFld(aux2, gFld("Top 10s", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "Ingest per day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index per Day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Ingest Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr segments", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Mailsource count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "User count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Size on Disk", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index", "archiving.html?solr161"))
		aux2 = insFld(aux1, gFld("<strong>Tokyo/Hong Kong</strong>", "archiving.html?Tokyo-Hong_Kong"))
			aux3 = insFld(aux2, gFld("solr segments", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "solr-161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr-162", "archiving.html?solr162"))
			aux3 = insFld(aux2, gFld("Servers (solr)", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "10.13.106.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.13.106.162", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.162", "archiving.html?solr161"))
			aux3 = insFld(aux2, gFld("Mailsources", "archiving.html?sum-solr-segments"))
			aux3 = insFld(aux2, gFld("Top 10s", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "Ingest per day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index per Day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Ingest Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr segments", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Mailsource count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "User count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Size on Disk", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index", "archiving.html?solr161"))
		aux2 = insFld(aux1, gFld("<strong>Sydney/Auckland</strong>", "archiving.html?Sydney-Auckland"))
			aux3 = insFld(aux2, gFld("solr segments", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "solr-161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr-162", "archiving.html?solr162"))
			aux3 = insFld(aux2, gFld("Servers (solr)", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "10.13.106.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.161", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.13.106.162", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "10.16.107.162", "archiving.html?solr161"))
			aux3 = insFld(aux2, gFld("Mailsources", "archiving.html?sum-solr-segments"))
			aux3 = insFld(aux2, gFld("Top 10s", "archiving.html?sum-solr-segments"))
				insDoc(aux3, gLnk("S", "Ingest per day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index per Day", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Ingest Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index Backlog", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "solr segments", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Mailsource count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "User count", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Size on Disk", "archiving.html?solr161"))
				insDoc(aux3, gLnk("S", "Index", "archiving.html?solr161"))
